In [1]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [2]:
import pandas as pd

df = pd.read_csv("train.csv")

df.shape

(9800, 18)

In [3]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62

## Project 1

In [4]:
# 1. Total number of orders

len(df["Order ID"].value_counts())

# out of 9800 records total hald them are orders are recorded.

4922

In [5]:
# 2. Total number of unique customers

len(df["Customer Name"].unique())

# total unique customers are 793 out of 9800.

793

In [6]:
# 3. Number of categories

len(df["Category"].unique())

# total 3 categories are rulling the entire 9800 sales

3

In [7]:
# 4. Number of sub-categories

len(df["Sub-Category"].unique())

# 3 categories and containing 17 sub categories

17

In [8]:
# 5. Highest sales value

df["Sales"].sort_values(ascending = False).head(1)

# Highest sale amount 9800 records is 22638.48

2697    22638.48
Name: Sales, dtype: float64

In [9]:
df["Sales"].max() # if only top 1 is asked we can use max. or for multiple we must use sort.

22638.48

In [10]:
# 6. Lowest sales value

df["Sales"].sort_values().head(1)

# Lowest sale amount 9800 records is 0.444

4101    0.444
Name: Sales, dtype: float64

In [11]:
df["Sales"].min() # if only least 1 is asked we can use min. or for multiple we must use sort.

0.444

In [12]:
# 7. Average sales value

print(df["Sales"].mean())

# out of 9800 records the average sale was sale was 230.7690594591837

230.7690594591837

# Poject 2

In [13]:
# Which category has the highest number of sales records?

df.groupby("Category")["Sales"].sum().sort_values(ascending= False)

# we can find that Tchnology is having highest sales compared to other categories.

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

In [14]:
# Which sub-category appears most frequently?

df["Sub-Category"].value_counts().head(1)

# Highest sub_category appered more frequent is Binders with total 1492 times

Sub-Category
Binders    1492
Name: count, dtype: int64

In [15]:
# Show the Top 5 highest sales transactions.

df.sort_values("Sales", ascending= False).head(5)

# complete rows of top 5 highest sale transaction

# All high transactions are been done in the category of Technology as feequent appered sub-category was Copiers.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2697,2698,CA-2015-145317,18-03-2015,23-03-2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480
6826,6827,CA-2017-118689,02-10-2017,09-10-2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
8153,8154,CA-2018-140151,23-03-2018,25-03-2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
2623,2624,CA-2018-127180,22-10-2018,24-10-2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
4190,4191,CA-2018-166709,17-11-2018,22-11-2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970

In [16]:
# Show the Top 5 lowest sales transactions.

df.sort_values("Sales").head(5)

# complete rows of top 5 lowest sale transaction

# All low transactions are been done in the category of Office Supplies as feequent appered sub-category was Binders.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
4101,4102,US-2018-102288,19-06-2018,23-06-2018,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444
9292,9293,CA-2018-124114,02-03-2018,02-03-2018,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,Texas,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556
8658,8659,CA-2017-168361,21-06-2017,25-06-2017,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,Illinois,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836
4711,4712,CA-2015-112403,31-03-2015,31-03-2015,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852
2106,2107,US-2015-152723,26-09-2015,26-09-2015,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,Texas,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876

In [17]:
# Which region appears most frequently?

df["City"].value_counts().head(3)

# New York City was the region appears most frequently

City
New York City    891
Los Angeles      728
Philadelphia     532
Name: count, dtype: int64

# Project 3

In [18]:
# Which customer generated the highest total sales?

df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(1)
# Sean Miller is the customer with total highest sales with 25043.05.

Customer Name
Sean Miller    25043.05
Name: Sales, dtype: float64

In [19]:
# Top 5 customers by total sales.

df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(5)

# only customer who has spend more than 20000 is Sean Miller out of top 5. rest all are in between 14000 to 20000

Customer Name
Sean Miller      25043.050
Tamara Chand     19052.218
Raymond Buch     15117.339
Tom Ashbrook     14595.620
Adrian Barton    14473.571
Name: Sales, dtype: float64

In [20]:
# Which state generated the highest total sales?

df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(1)

# California generated the highest total with sales of 446306.4635

State
California    446306.4635
Name: Sales, dtype: float64

In [21]:
# Which region generated the highest total sales?

df.groupby("Region")["Sales"].sum().sort_values(ascending=False).head(1)

# West region generated the highest total with sales of 710219.6845

Region
West    710219.6845
Name: Sales, dtype: float64

In [22]:
# Which ship mode is used most frequently?

df["Ship Mode"].value_counts().head(1)

# most frequently used ship mode was Standard Class with a count of 5859.

Ship Mode
Standard Class    5859
Name: count, dtype: int64

In [23]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

# Project 4

In [51]:
# Which year generated the highest total sales?

df["Order Date"] = pd.to_datetime(df["Order Date"])

df["year"] = df["Order Date"].dt.year

df.groupby("year")["Sales"].sum().sort_values(ascending=False).head(1)

# 2018 has generated highest total sales of 722052.0192

year
2018    722052.0192
Name: Sales, dtype: float64

In [25]:
# Top 5 cities by total sales.

df.groupby("City")["Sales"].sum().sort_values(ascending=False).head(5)

# New york topped in total sales compared to other cities followed with Los Angeles, Seattle, San Francisco and Philadelphia. Top 1st city is more than twice to the top 5th city.

City
New York City    252462.547
Los Angeles      173420.181
Seattle          116106.322
San Francisco    109041.120
Philadelphia     108841.749
Name: Sales, dtype: float64

In [26]:
# Top 5 states by total sales.

df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(5)

# California topped in ttal sales compared to other cities followed with New York, Texas, Washington and Washington. Top 1st State is almost4 times to the top 5th city.

State
California      446306.4635
New York        306361.1470
Texas           168572.5322
Washington      135206.8500
Pennsylvania    116276.6500
Name: Sales, dtype: float64

In [27]:
# Which segment generated the highest total sales?

df.groupby("Segment")["Sales"].sum().sort_values(ascending=False).head(1)

# Consumer segment generated the highest total sales of 1148060.531

Segment
Consumer    1148060.531
Name: Sales, dtype: float64

In [28]:
# Which category generated the highest total sales?

df.groupby("Category")["Sales"].sum().sort_values(ascending=False).head(1)

# Technology generated the highest total sales of 827455.873

Category
Technology    827455.873
Name: Sales, dtype: float64

In [71]:
# Which Sub-Category generated the highest total sales?

df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(1)

# Phones are having the highest sales with 327782.448, where we can increase the production of phones and work on other inventory too

Sub-Category
Phones    327782.448
Name: Sales, dtype: float64

In [74]:
df.groupby("Segment")["Sales"].sum().sort_values().head(1)

Segment
Home Office    424982.1769
Name: Sales, dtype: float64

# Project 5

In [75]:
# Which ship mode generated the highest total sales?

df.groupby("Ship Mode")["Sales"].sum().sort_values(ascending=False).head(1)

# Standard Class ship mode generated the highest total sales with 1340831.307

Ship Mode
Standard Class    1340831.307
Name: Sales, dtype: float64

In [86]:
# Top 5 products by total sales.

df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(5)

# The top 5 products contribute significantly to overall revenue. The highest-selling product generated Canon imageCLASS 2200 Advanced Copier sales of 61599.824, indicating strong customer demand.

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
Name: Sales, dtype: float64

In [84]:
# Top 5 cities by average sales

df.groupby("City")["Sales"].mean().sort_values(ascending=False).head(5)

# Jamestown was topped among other cities with average sales of 2354.395 followed by Cheyenne, Bellingham, Independence and Burbank

City
Jamestown       2354.395000
Cheyenne        1603.136000
Bellingham      1263.413333
Independence    1208.685000
Burbank         1082.386000
Name: Sales, dtype: float64

# Project Summary

# Findings 1

#### 2018 generated the highest total sales with 722052.0192.2018 generated the highest total sales with 722052.0192.

# Finding 2

#### November generated the highest total sales with 350161.711.

# Finding 3

#### February generated the lowest total sales with 59371.1154.

# Finding 4

#### Technology generated the highest total sales with 827455.873.

# Finding 5

#### Phones generated the highest total sales with 327782.448.

# Finding 6

#### Highest sales state?

# Finding 7

#### West generated the highest total sales with 710219.6845.

# Finding 8

#### Sean Miller generated the highest total sales with 25043.05.

# Finding 9

#### Standard Class was the most frequently used shipping mode.

# Finding 10

#### Canon imageCLASS 2200 Advanced Copier generated the highest product sales with 61599.824.

# Recommendations

Recommendation 1

Increase inventory planning and promotional efforts before November and December because these months consistently generate the highest sales.

Recommendation 2

Focus marketing and sales efforts on Technology products, especially Phones, as they contribute the highest revenue.

Recommendation 3

Analyze the reasons behind low February sales and consider seasonal campaigns or discounts to improve performance.